### PR TITLE
Test: 🚨 [Expected CI Failure] Add unit tests for Agent EMPTY_RESULT handling (Depends on #14305)

### PR DESCRIPTION
**Pull request by ParasSondhi**
### What problem does this PR solve?

This PR introduces the comprehensive unit test suite for the `EMPTY_RESULT` Agent trapdoor logic implemented in PR #14305.

**Context on PR Isolation & CI Status:**
These tests have been deliberately separated from the core implementation PR to isolate an environmental teardown anomaly in the CI pipeline without blocking the main feature review. 

To prevent this stacked test file from causing a hard setup failure on unmerged branches, the `ToolExecutionState` import has been gated inside a `try...except` block. If PR #14305 is not yet present, the new tests will gracefully **skip** rather than crash. This allows the rest of the repository's test suite to complete running, directly exposing the resource warnings during the session teardown phase.

The resulting CI logs pass the test suite (`972 passed, 30 skipped`) but surface the underlying loop cleanup warnings at the very end:
* `ResourceWarning: unclosed <socket.socket fd=15, family=1, type=1, proto=0>`
* `ResourceWarning: unclosed <socket.socket fd=14, family=1, type=1, proto=0>`
* `ResourceWarning: unclosed event loop <_UnixSelectorEventLoop running=False closed=False debug=False>`

*Note: This PR is strictly dependent on the structural changes introduced in #14305 and will automatically activate with 100% local pass coverage once that PR is merged.*

### Type of change

- [x] Other (please describe): Unit Tests & CI Diagnostic Profile

### CODE REVIEW

**Comment by User002721** [comment]
@buua436 Dropping the regression tests here to cover the non-streaming, streaming, empty-result, real-error cases and conversational bypass based on your feedback for the trapdoor logic. 

I isolated them into this separate PR because the automated CI environment surfaces loopback socket warnings during the final session teardown phase. To prevent an unmerged dependency from hard-failing the pipeline signal, I've wrapped the `ToolExecutionState` import in a `try...except` block so these new tests gracefully skip on setup if **#14305** isn't merged yet. 

This allows the full suite to complete running (`968 passed, 29 skipped`) while cleanly exposing the underlying `pytest_asyncio` socket resource warnings (`fd=14`, `fd=15`) at the very end of the log. 

Let me know if the test logic itself looks solid to you, or if you need any adjustments!

**Comment by KevinHuSh** [comment]
Appreciatioons!

CI failure.

```
==================================== ERRORS ====================================
__________ ERROR at setup of test_invoke_async_empty_result_trapdoor ___________
test/unit_test/agent/sandbox/test_agent_false_action.py:12: in agent_setup
    ???
E   ImportError: cannot import name 'ToolExecutionState' from 'agent.component.agent_with_tools' (/home/infiniflow/runners_work/inf26-f38f64522611/ragflow/ragflow/agent/component/agent_with_tools.py)
```

**Comment by User002721** [comment]
@KevinHuSh Thanks for taking a look! 

The immediate `ImportError` you pointed out was due to the missing `ToolExecutionState` Enum from the unmerged **PR #14305**. To prevent this from masking the true environment behavior—and following the latest review from CodeRabbit—I wrapped the import in a `try...except` block to gate the execution.

Now, the tests safely skip on setup if the core PR isn't merged yet. This allows the overall pipeline to complete running (`968 passed, 29 skipped`), which successfully surfaces the exact resource warnings at the very end of the run:

`ResourceWarning: unclosed <socket.socket fd=15...>`
`ResourceWarning: unclosed <socket.socket fd=14...>`

This confirms the red status on this PR is tied to asynchronous teardown warnings during event loop cleanup transitions, rather than a hard setup crash in the test file itself. Once #14305 is merged into `main`, these tests will automatically resolve their imports and run fully.

**Comment by JinHai-CN** [comment]
@ParasSondhi Since previous PR includes a binary file which is very big. So, I reset the head of main branch. Would you please re-submit the commit from current HEAD of main branch? Thank you very much.

**Comment by User002721** [comment]
@coderabbitai resume

File: test/unit_test/agent/sandbox/test_agent_false_action.py [hunk 1]
```diff
@@ -0,0 +1,146 @@
...
+        return "Hello! I am ready to assist you today."
+    mock_agent._generate_async = mock_greeting_generate
+
+    with patch.object(mock_agent, '_get_tool_execution_state', return_value=ToolExecutionState.NOT_CALLED) as mock_get_state:
+        await mock_agent._invoke_async(user_prompt="Hi")
+        
+        logger.debug("Evaluating assertions for normal greeting state.")
+        mock_get_state.assert_called_once()
+        assert mock_agent.output("content") == "Hello! I am ready to assist you today."
+        assert mock_agent.error() is None
```
[the remark this answers is not in the document]
Comment (ParasSondhi) [reply test/unit_test/agent/sandbox/test_agent_false_action.py:149]: I intentionally removed this specific test during the latest refactor because it was fundamentally flawed. Leaving a quick note here on why it was removed:

The `test_invoke_async_fake_action_claim_trapdoor` test was originally generating a "false positive" pass due to state bleed from a shared module-level fixture. Here is exactly why we cannot test that specific scenario in this mock environment:

* **Python Level vs. Prompt Level:** In `agent_with_tools.py`, the Python trapdoor explicitly intercepts the `EMPTY_RESULT` state. However, it intentionally passes the `NOT_CALLED` state through without interference so that standard greetings can work normally (which is successfully verified in the current Case 5).
* **The Mocking Limitation:** Stopping the LLM from hallucinating an action during a `NOT_CALLED` state is handled entirely by the `safety_prompt` injected into the system instructions, *not* by Python-level intervention. 
* **The False Positive:** Because these unit tests use a mocked LLM that ignores injected prompts and returns hardcoded text, it is impossible to write a valid Python test that asserts LLM prompt adherence. The previous version of this test only passed because it was accidentally reading leftover `"ACTION_NOT_PERFORMED"` data in the `mock_agent`'s memory from a previous test execution. 

The remaining 5 test cases cleanly map to the 4 actual Enum states in the Python code (with `EMPTY_RESULT` covered twice for both the batch and streaming paths). This provides 100% accurate coverage of the actual Python logic matrix.

**Comment by User002721** [comment]
as PR#14305 is closed, This PR was completely dependent on that so i have to close this PR.
