### PR TITLE
fix(llm): guard BaiduYiyanEmbed key against non-JSON / JSON non-object

### LINKED ISSUE #17504: [Bug]: BaiduYiyanEmbed provider crashes with AttributeError when key is a JSON non-object (embed-side companion of #17389; same pattern as #17204 / #17373 / #17456 / #17458 / #17463)
### Self Checks

- [x] I have searched for existing issues, including closed ones.
- [x] I confirm that I am using English to submit this report.
- [x] Non-English title submissions will be closed directly.
- [x] I have not modified the template and have filled in all the required fields.

### RAGFlow workspace code commit ID

`main` @ `ee388b0fa` (also reproducible on any `v0.26.x` since the BaiduYiyanEmbed class was introduced).

### RAGFlow image version

`v0.26.4` (also reproducible on the current dev image).

### Other environment information

- Provider: `BaiduYiyan` (factory name) — see `conf/llm_factories.json` and `conf/models/baidu.json`.
- Affected class: `BaiduYiyanEmbed` (the embedding side of the BaiduYiyan / Qianfan provider) — `rag/llm/embedding_model.py:1019-1029`
- Companion class (already fixed by PR #17390 / commit `c6d1af4b1`): `BaiduYiyanChat` — `rag/llm/chat_model.py:1189-1196`. PR #17390 introduced the `_resolve_qianfan_credentials` helper in `rag/llm/key_utils.py` and wired `BaiduYiyanChat.__init__` through it. **However, PR #17390 only fixed the chat side — the embed side has the same shape of bug and was not touched.**

### Actual behavior

The `BaiduYiyanEmbed.__init__` method parses its API key as JSON to extract the `yiyan_ak` and `yiyan_sk` fields:

```python
# rag/llm/embedding_model.py:1025-1027
key = json.loads(key)
ak = key.get("yiyan_ak", "")
sk = key.get("yiyan_sk", "")
```

There is **no try/except** around the `json.loads(key)` call. A user pasting any input that is NOT a JSON object — for example:

- `key = '[1, 2, 3]'` parses to a list → `.get("yiyan_ak", "")` raises `AttributeError: 'list' object has no attribute 'get'`
- `key = '"a plain string"'` parses to a string → same `AttributeError`
- `key = 'null'` parses to `None` → same `AttributeError`
- `key = '42'` parses to `int` → same `AttributeError`
- `key = 'true'` parses to `bool` → same `AttributeError`
- `key = '3.14'` parses to `float` → same `AttributeError`

In every case the call site raises an unhandled `AttributeError` that bubbles up as a 500 in the API and a stack trace in the server log. This is the **same class of bug** that PR #17215 fixed for Azure, PR #17377 fixed for Bedrock, PR #17457 fixed for VolcEngine/Ark, PR #17459 fixed for OpenRouter, and PR #17464 fixed for GoogleCV.

The BaiduYiyan / Qianfan provider REQUIRES a JSON object key (per `conf/models/baidu.json`). A user pasting a plain Baidu API key like `"bce-v3/ALTAK-.../..."` (the most common mistake: copying from the Qianfan console) OR a JSON non-object (e.g. a JSON list) gets a 500 from inside `rag/llm` internals — no indication of what they did wrong.

### Expected behavior

A user pasting any non-BaiduYiyan-shaped key (a plain API key, a JSON list, a JSON number, a malformed JSON object) should get a **clear, actionable error** at provider-init time, not a 500. The provider REQUIRES a JSON object, so a non-object input should raise a clear `ModelException(retryable=False)` with a message that names the required fields (`yiyan_ak`, `yiyan_sk`) and points at `conf/models/baidu.json`.

### Steps to reproduce

1. Start RAGFlow `v0.26.4` (any deployment).
2. Try to add a BaiduYiyan / Qianfan embedding model provider via the admin UI (or `POST /api/v1/llm/factories`).
3. Paste any of these into the API key field:
   - A JSON array like `["a", "b"]` — crashes with `AttributeError: 'list' object has no attribute 'get'`.
   - A JSON number like `42` — same crash.
   - A JSON string like `"a plain string"` (with quotes) — same crash.
   - A JSON null `null` — same crash.
   - A JSON bool `true` — same crash.
4. The server log shows an unhandled `AttributeError`. The admin UI shows a generic 500 with no actionable hint.

### Expected error surface

After the fix, a JSON non-object should raise the same clear error as the chat-side helper (e.g. `ModelException(retryable=False)` with a message like: `"BaiduYiyan key must be a JSON object, got <type>. See conf/models/baidu.json for the model class."`).

### Coordination note

PR #17390 (commit `c6d1af4b1`) added a `_resolve_qianfan_credentials` helper in `rag/llm/key_utils.py` and wired `BaiduYiyanChat.__init__` through it. This fix uses the **same helper** for the embed side. If PR #17390 lands first, this PR can be rebased to drop the helper re-addition. If this PR lands first, PR #17390 can be rebased to drop its helper addition (just keeping the chat-side wire-up). Either order resolves to the same final state. The maintainers can decide the merge order.

### Additional information

**Affected files and line numbers** (in commit `ee388b0fa`):

| File | Class | Lines | Current state |
|---|---|---|---|
| `rag/llm/embedding_model.py` | `BaiduYiyanEmbed` | 1019-1029 | **CRASHES** on non-JSON or JSON non-object |

The fix is a single-line wire-up in `BaiduYiyanEmbed.__init__` to use the existing `_resolve_qianfan_credentials` helper from `rag/llm/key_utils.py` (the same helper PR #17390 added for the chat side). If the helper is not yet on upstream main when this PR is opened, this PR also re-adds the helper (mirroring PR #17390 verbatim) so the embed site is self-contained.

Regression tests covering:

1. Plain string key → `ModelException` (the provider REQUIRES a JSON object; no plain-key fallback)
2. JSON dict with both fields → return parsed fields
3. JSON dict missing `yiyan_ak` or `yiyan_sk` → default to empty string (preserves tolerance)
4. JSON list, number, string, null, bool → `ModelException` (the new fix)
5. Bad JSON string → `ModelException` (the new fix)
6. Helper propagates the right fields to `BaiduYiyanEmbed.__init__` so the class gets exactly what it needs

A PR fixing this is in progress.

### PR DESCRIPTION
**Pull request by Harsh23Kashyap**
## Summary

Closes #17504. The `BaiduYiyanEmbed` (Baidu Qianfan embedding) provider in `rag/llm/embedding_model.py:1019-1029` does an unguarded `json.loads(key).get("yiyan_ak", "")` followed by `.get("yiyan_sk", "")`:

```python
# rag/llm/embedding_model.py:1025-1027
key = json.loads(key)
ak = key.get("yiyan_ak", "")
sk = key.get("yiyan_sk", "")
```

The provider REQUIRES a JSON object key (per `conf/models/baidu.json`). A user pasting a plain Baidu API key like `"bce-v3/ALTAK-.../..."` (the most common mistake: copying from the Qianfan console directly) crashes with `json.decoder.JSONDecodeError: Expecting value: line 1 column 1 (char 0)` from inside `rag/llm` internals. A user pasting a JSON non-object (e.g. `"[1,2,3]"`, `"42"`, `'"hi"'`, `"true"`, `"null"`) parses fine and then crashes on the subsequent `.get(...)` call with `AttributeError: 'list' object has no attribute 'get'`.

This is the **embed-side companion** of #17389 / PR #17390 (which fixed the same shape of bug on the chat side via the `_resolve_qianfan_credentials` helper in `rag/llm/key_utils.py`).

## Changes

**1 helper, 1 call site, 1 test file:**

- `rag/llm/key_utils.py` — add `_resolve_qianfan_credentials(key)`. Returns the parsed dict on success; raises `ModelException(retryable=False)` on any non-JSON or JSON non-object input. The helper body is identical to the chat-side helper introduced by PR #17390.
- `rag/llm/embedding_model.py` — `BaiduYiyanEmbed.__init__` calls the helper instead of the bare `json.loads(key).get(...)` calls. The downstream `key.get("yiyan_ak", "")` / `.get("yiyan_sk", "")` calls are unchanged.
- `test/unit_test/rag/llm/test_baiduyiyan_embed_json_key_fallback.py` — 14 p0 regression tests (9 on the helper directly, 5 on the `BaiduYiyanEmbed` constructor). The qianfan SDK is stubbed at `sys.modules["qianfan"]` level (same workaround as PR #17390) to sidestep a pre-existing baidubce/litellm Python 3.13 incompatibility in the test venv.

## Coordination note

This PR re-adds the same `_resolve_qianfan_credentials` helper that PR #17390 added for the chat side. Since this branch is off `upstream/main` (which doesn't have PR #17390 yet), the helper is required for the embed-side wire-up to be self-contained. There are two valid merge orderings:

1. **If PR #17390 lands first**, this PR can be rebased to drop the helper re-addition (keeping only the embed-side wire-up at `embedding_model.py:1025`). The helper will then be imported from `key_utils.py` as added by PR #17390.
2. **If this PR lands first**, PR #17390 can be rebased to drop its helper addition (just keeping the chat-side wire-up at `chat_model.py:1189`). The helper will then be imported from `key_utils.py` as added by this PR.

Either ordering resolves to the same final state. The maintainers can decide the merge order.

## Behavior unchanged for the existing happy path

- JSON dict with both `yiyan_ak` + `yiyan_sk` → `ak = parsed["yiyan_ak"]`, `sk = parsed["yiyan_sk"]` (unchanged).
- JSON dict missing `yiyan_ak` or `yiyan_sk` → defaults to empty string (unchanged from the pre-fix `dict.get(k, "")` calls).
- Pre-existing `qianfan.Embedding(ak=ak, sk=sk)` call shape is unchanged.

No public API change. No data-model change. No migration.

## Testing

```
$ .venv/bin/python -m pytest test/unit_test/rag/llm/test_baiduyiyan_embed_json_key_fallback.py -v
============================== 14 passed in 3.11s ==============================
```

Plus the existing 23 `test_embedding_model.py` tests pass unchanged (37 / 37 in the combined run).

```
$ ruff check <3 changed files>
All checks passed!

$ ruff format --check <3 changed files>
3 files already formatted
```

## Cross-references

- The provider bug was reported in #17504 with full reproduction steps.
- The same shape of bug on the chat side was previously fixed in:
  - PR #17390 (BaiduYiyan / Qianfan chat, #17389)
  - PR #17215 (Azure-OpenAI, #17204)
  - PR #17377 (Bedrock, #17373)
  - PR #17457 (VolcEngine / Ark, #17456)
  - PR #17459 (OpenRouter, #17458)
  - PR #17464 (GoogleCV, #17463)
- After this PR, no remaining unfixed LLM-provider JSON-decode sites in `rag/llm/` that we own — the only remaining site is the chat-side `GoogleChat` (`rag/llm/chat_model.py:1284`), which is owned by @glu000 via #15994 and is intentionally OUT OF SCOPE.

### CODE REVIEW

File: rag/llm/key_utils.py [hunk 1]
```diff
@@ -31,4 +34,59 @@ def _normalize_replicate_key(key):
...
+        try:
+            payload = json.loads(key)
+        except (json.JSONDecodeError, TypeError):
+            logging.warning(
+                "BaiduYiyan key is not valid JSON; expected a JSON object with 'yiyan_ak' and 'yiyan_sk' (see conf/models/baidu.json).",
+            )
+            raise ModelException(
+                'BaiduYiyan requires a JSON key with at least \'yiyan_ak\' and \'yiyan_sk\'. Example: {"yiyan_ak": "...", "yiyan_sk": "..."}. See conf/models/baidu.json for the model class.',
+                retryable=False,
+            )
```
[the remark this answers is not in the document]
Comment (Harsh23Kashyap) [reply rag/llm/key_utils.py]: Fixed in commit `06182084e`:

`_resolve_qianfan_credentials` in `rag/llm/key_utils.py` now binds the caught exception as `exc` and chains it via `raise ModelException(...) from exc`, satisfying Ruff B904 and preserving the original parser error in the traceback.

14 tests in test_baiduyiyan_embed_json_key_fallback.py still pass; ruff check + ruff format --check both clean.

**Comment by JinHai-CN** [comment]
@Harsh23Kashyap Would you please resolve the conflicts?

**Comment by Harsh23Kashyap** [comment]
Cherry-picked onto current upstream/main and force-pushed. Resolved import conflicts in embedding_model.py. PR is current with main.

**Comment by JinHai-CN** [comment]
@Harsh23Kashyap would you please resolve the conflicts?
