### ISSUE TITLE
[Bug]: v0.15.1-46 ERROR Book chunk /  Pdf object has no attribute page_chars

### ISSUE THREAD

**Issue by dromeuf** [infiniflow/ragflow#4345]
### Is there an existing issue for the same bug?

- [X] I have checked the existing issues.

### RAGFlow workspace code commit ID

e24af69e96304a0767129b98af3e929cf1c06930

### RAGFlow image version

v0.15.1-46-g8674156d slim

### Other environment information

```Markdown
Linux 5.15.167.4-microsoft-standard-WSL2
```

### Actual behavior

Hi, When I try to import this file with Book chunking I get error PDF :
[](https://filesender.renater.fr/?s=download&token=be91b215-c855-410b-8483-7cd25bb3c11b)

Kinds regards, David.

09:19:51 Page(121~133): Done (0.45s)
09:19:51 Task has been received.
09:19:51 Page(133~145): OCR started
09:19:54 Page(133~145): [**ERROR]Internal server error while chunking: Pdf object has no attribute page_chars
09:19:54 [ERROR][Exception]: 'Pdf' object has no attribute 'page_chars'**
09:19:54 Task has been received.
09:19:54 Page(145~157): OCR started
09:20:00 Page(145~157): OCR finished (6.40s)
09:20:10 Page(145~157): Layout analysis (9.44s)

### Steps to reproduce

```Markdown
idem
```

**Comment by JinHai-CN** [comment]
Hi David, would you please attach the file RAGFlow failed to parse?

**Comment by KevinHuSh** [comment]
Possibly, it fails to fetch the downloaded file.
What about redoing parsing again?

**Comment by dromeuf** [comment]
> Hi David, would you please attach the file RAGFlow failed to parse?

oh I had loaded it on a DL but forgot to add the link to the document.
You can download it here : https://filesender.renater.fr/?s=download&token=be91b215-c855-410b-8483-7cd25bb3c11b

Kind regards, David.

PS: I've carried out several tests with different embedding and LLM recovery model configurations, assigning scores from 0 to 5  for the quality of the responses. I'll provide feedback on the question thread.

**Comment by alanOO7** [comment]
I also have the same problem

**Comment by SummerHuii** [comment]
please try solve this problem.

**Comment by KevinHuSh** [comment]
Could you share us with the file?
kai.hu@infiniflow.org

**Comment by mustangxu** [comment]
> Could you share us with the file? [kai.hu@infiniflow.org](mailto:kai.hu@infiniflow.org)

@KevinHuSh I met the same issue in version 0.24.0, self-hosted cpu, even after bumping pdfplumber to 0.11.0+ and pypdf to 6.9.0+ as well, referring to https://github.com/infiniflow/ragflow/issues/3335. I have emailed you the file.

error log:
```
Traceback (most recent call last):
  File "/ragflow/rag/svr/task_executor.py", line 1214, in handle_task
    await do_handle_task(task)
  File "/ragflow/common/connection_utils.py", line 74, in async_wrapper
    return await func(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/ragflow/rag/svr/task_executor.py", line 1111, in do_handle_task
    chunks = await build_chunks(task, progress_callback)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/ragflow/common/connection_utils.py", line 74, in async_wrapper
    return await func(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/ragflow/rag/svr/task_executor.py", line 272, in build_chunks
    cks = await thread_pool_exec(
          ^^^^^^^^^^^^^^^^^^^^^^^
  File "/ragflow/common/misc_utils.py", line 132, in thread_pool_exec
    return await loop.run_in_executor(_thread_pool_executor(), func)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/root/.local/share/uv/python/cpython-3.12.12-linux-x86_64-gnu/lib/python3.12/asyncio/futures.py", line 289, in __await__
    yield self  # This tells Task to wait for completion.
    ^^^^^^^^^^
  File "/root/.local/share/uv/python/cpython-3.12.12-linux-x86_64-gnu/lib/python3.12/asyncio/tasks.py", line 385, in __wakeup
    future.result()
  File "/root/.local/share/uv/python/cpython-3.12.12-linux-x86_64-gnu/lib/python3.12/asyncio/futures.py", line 202, in result
    raise self._exception.with_traceback(self._exception_tb)
  File "/root/.local/share/uv/python/cpython-3.12.12-linux-x86_64-gnu/lib/python3.12/concurrent/futures/thread.py", line 59, in run
    result = self.fn(*self.args, **self.kwargs)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/ragflow/rag/app/naive.py", line 863, in chunk
    sections, tables, pdf_parser = parser(
                                   ^^^^^^^
  File "/ragflow/rag/app/naive.py", line 91, in by_deepdoc
    sections, tables = pdf_parser(filename if not binary else binary, from_page=from_page, to_page=to_page, callback=callback)
                       ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/ragflow/rag/app/naive.py", line 575, in __call__
    self.__images__(filename if not binary else binary, zoomin, from_page, to_page, callback)
  File "/ragflow/deepdoc/parser/pdf_parser.py", line 1438, in __images__
    for i in range(len(self.page_chars))
                       ^^^^^^^^^^^^^^^
AttributeError: 'Pdf' object has no attribute 'page_chars'
```

**Comment by ZhangJunGuo1** [comment]
@mustangxu Hello, I am also using version 0.24 and have encountered this issue. Has it been resolved

**Comment by mustangxu** [comment]
> [@mustangxu](https://github.com/mustangxu) Hello, I am also using version 0.24 and have encountered this issue. Has it been resolved

NOT even fixed in 0.25.1

**Comment by KevinHuSh** [comment]
> page_chars

Is this only for a specific PDF file or all the PDFs?
Please send me the file if it's convenient: kai.hu@infiniflow.org

**Comment by mustangxu** [comment]
> > page_chars
> 
> Is this only for a specific PDF file or all the PDFs? Please send me the file if it's convenient: [kai.hu@infiniflow.org](mailto:kai.hu@infiniflow.org)

I resend the file to you @KevinHuSh 

<img width="685" height="581" alt="Image" src="https://github.com/user-attachments/assets/49222b69-6492-4f77-a50b-6c32b8072e74" />

**Comment by ZhangJunGuo1** [comment]
all the PDFs

**Comment by ZhangJunGuo1** [comment]
@KevinHuSh 
My usage scenario is:
Firstly, 50 docx files were transmitted and parsed, all of which were successful
2. Another user uploaded 4 PDFs (external MinerU), but the parsing was stuck at 80% (Start to generate keywords for every chunk...). Due to some adjustments to the knowledge base configuration, it took about 3 hours to complete
3. Docx parsing is fine, MinerU parsing PDF is fine
4. The third user uploaded a PDF file for parsing (deepdoc), but the direct parsing failed. The 'Pdf' object has no attribute 'page_chars'
There is a slight deviation in time
The problem code is suspected to be:
    def __images__(self, fnm, zoomin=3, page_from=0, page_to=299, callback=None):
        self.lefted_chars = []
        self.mean_height = []
        self.mean_width = []
        self.boxes = []
        self.garbages = {}
        self.page_cum_height = [0]
        self.page_layout = []
        self.page_from = page_from
        start = timer()
        try:
            with sys.modules[LOCK_KEY_pdfplumber]:
                with pdfplumber.open(fnm) if isinstance(fnm, str) else pdfplumber.open(BytesIO(fnm)) as pdf:
                    self.pdf = pdf
                    self.page_images = [p.to_image(resolution=72 * zoomin, antialias=True).annotated for i, p in enumerate(self.pdf.pages[page_from:page_to])]

                    try:
                        self.page_chars = [[c for c in page.dedupe_chars().chars if self._has_color(c)] for page in self.pdf.pages[page_from:page_to]]
                    except Exception as e:
                        logging.warning(f"Failed to extract characters for pages {page_from}-{page_to}: {str(e)}")
                        self.page_chars = [[] for _ in range(page_to - page_from)]  # If failed to extract, using empty list instead.

                    self.total_page = len(self.pdf.pages)

        except Exception as e:
            logging.exception(f"RAGFlowPdfParser __images__, exception: {e}")

**Comment by ZhangJunGuo1** [comment]
@KevinHuSh I found the real error: RAGFlowPdfParser __images__, exception: Failed to load page

<img width="1920" height="1440" alt="Image" src="https://github.com/user-attachments/assets/d4aa728c-7589-4b96-b053-27447fa6fa58" />
Is there any solution
