### ISSUE TITLE
[Question]:  Fails to add VLM and image chat in v0.22.1 (works in v0.20.5)

### ISSUE THREAD

**Issue by xsxustc** [infiniflow/ragflow#12036]
### Self Checks

- [x] I have searched for existing issues [search for existing issues](https://github.com/infiniflow/ragflow/issues), including closed ones.
- [x] I confirm that I am using English to submit this report ([Language Policy](https://github.com/infiniflow/ragflow/issues/5910)).
- [x] Non-english title submitions will be closed directly ( 非英文标题的提交将会被直接关闭 ) ([Language Policy](https://github.com/infiniflow/ragflow/issues/5910)).
- [x] Please do not modify this template :) and fill in all the required fields.

## Environment

* **RAGFlow versions**:

  * v0.20.5 (working)
  * v0.22.1 (issue)
* **Model type**: OpenAI-API-Compatible
* **Model**: Locally deployed DeepSeek-OCR (OCR / VLM)
* **Deployment**: Local / private / docker

---

## Description

The same locally deployed **DeepSeek-OCR** model behaves differently across versions:

### 1. Cannot add model in v0.22.1

When adding an `OpenAI-API-Compatible / DeepSeek-OCR` model, it fails with:

```log
Fail to access model(OpenAI-API-Compatible/DeepSeek-OCR).
Completions.create() got an unexpected keyword argument 'unused'
```

The model can be added successfully in v0.20.5.

---

### 2. Image chat fails in v0.22.1 (migrated model)

This model was migrated from v0.20.5:

* Text-only chat: works
* Image + text chat: fails

Error log:

```log
'Request' object has no attribute 'file'
```

Image chat works in v0.20.5.

---

## Questions / Clarification

At this point I’m not sure whether this is expected behavior or an integration issue on my side. I’d appreciate clarification on:

1. Were there any changes in v0.22.1 regarding **OpenAI-compatible parameters** or **multimodal request handling**?
2. Do these errors indicate that additional adaptation is required for local VLM / OCR models?
3. Is there a recommended way to integrate **custom OpenAI-compatible VLM/OCR models** in v0.22.1?

---

## Expectation

* Clarify whether this is a **behavior change / limitation in the project**, or an issue with my integration
* If adaptation is required, guidance or documentation would be very helpful

---

**Comment by xsxustc** [comment]
@dosu thanks for the explanation.

I’d like to clarify the second issue (`'Request' object has no attribute 'file'`) more precisely.

This error occurs **when using the RAGFlow Web UI**. The image upload completes, but the error is thrown **before the user sends any chat message**. At this stage, no message payload is constructed yet, so this is not related to base64-encoded image data in the message content.

Since the same UI workflow works correctly in v0.20.5, this appears to be a UI/backend regression in v0.22.1 during the image upload handling phase.

Just to confirm: this issue happens without any custom API calls or model-side changes — only through the built-in UI.

Thanks.

**Comment by Magicbook1108** [comment]
any logs for second issue? screen shot please

**Comment by yongtenglei** [comment]
Hi, @xsxustc 

I can upload images and chat with qwen3-vl-plus launching with latest source code.

<img width="1673" height="660" alt="Image" src="https://github.com/user-attachments/assets/254e2983-db79-4bcb-a4b8-ab94f929f36d" />
