### ISSUE TITLE
[Question]: AttributeError("module 'agent.tools' has no attribute 'AnswerParam'")

### ISSUE THREAD

**Issue by dededelala** [infiniflow/ragflow#9141]
### Self Checks

- [x] I have searched for existing issues [search for existing issues](https://github.com/infiniflow/ragflow/issues), including closed ones.
- [x] I confirm that I am using English to submit this report ([Language Policy](https://github.com/infiniflow/ragflow/issues/5910)).
- [x] Non-english title submitions will be closed directly ( 非英文标题的提交将会被直接关闭 ) ([Language Policy](https://github.com/infiniflow/ragflow/issues/5910)).
- [x] Please do not modify this template :) and fill in all the required fields.

### Describe your problem

After upgrade to v0.19.1-290-gd9fe279d slim,my agents reported “AttributeError("module 'agent.tools' has no attribute 'AnswerParam'")” after clicking "Run".

**Comment by yangyazhou97** [comment]
nightly-slim version ,  there is also a "AttributeError("module 'agent.tools' has no attribute 'AnswerParam'")” error when creating a new agent.

**Comment by cariousWhite** [comment]
This issue still persists, even when using the latest nightly image.
