### ISSUE TITLE
[Question]: RAGFlowJsonParser._json_split() missing 2 required positional arguments: current_path and chunks

### ISSUE THREAD

**Issue by rpopplewell** [infiniflow/ragflow#4034]
### Describe your problem

I'm working with v0.14.1-slim from a docker image as described in the README.md. In attempting to parse a json file we get the following error: 
[ERROR]Internal server error while chunking: RAGFlowJsonParser._json_split() missing 2 required positional arguments: current_path and chunks

This function appears to be under `/deepdoc/parser/json_parser.py`
Here's the traceback:
```Traceback (most recent call last):
  File "/ragflow/rag/svr/task_executor.py", line 449, in handle_task
    do_handle_task(task)
  File "/ragflow/rag/svr/task_executor.py", line 388, in do_handle_task
    cks = build(r)
  File "/ragflow/rag/svr/task_executor.py", line 200, in build
    cks = chunker.chunk(row["name"], binary=binary, from_page=row["from_page"],
  File "/ragflow/rag/app/naive.py", line 258, in chunk
    sections = JsonParser(int(parser_config.get("chunk_token_num", 128)))(binary)
  File "/ragflow/deepdoc/parser/json_parser.py", line 24, in __call__
    chunks = self.split_json(json_data, True)
  File "/ragflow/deepdoc/parser/json_parser.py", line 95, in split_json
    chunks = self._json_split(self._list_to_dict_preprocessing(json_data))
TypeError: RAGFlowJsonParser._json_split() missing 2 required positional arguments: 'current_path' and 'chunks'```

**Comment by zifeiYv** [comment]
[Codes](https://github.com/infiniflow/ragflow/blob/main/deepdoc/parser/json_parser.py#L95) have already been updated, try to upgrade your project maybe?

**Comment by rpopplewell** [comment]
> [Codes](https://github.com/infiniflow/ragflow/blob/main/deepdoc/parser/json_parser.py#L95-L99) have already been updated, try to upgrade your project maybe?

The docker image was not. Your link reflects the source code but not the docker image. I'm AFK but I'll pull a fresh image tomorrow.

**Comment by KevinHuSh** [comment]
Pull the version 'nightly' of docker image.
