### ISSUE TITLE
[Question]: After upgrading image form 0.19.1 to 0.20.1, code of agent tool failed

### ISSUE THREAD

**Issue by qazwsx18** [infiniflow/ragflow#9398]
### Self Checks

- [x] I have searched for existing issues [search for existing issues](https://github.com/infiniflow/ragflow/issues), including closed ones.
- [x] I confirm that I am using English to submit this report ([Language Policy](https://github.com/infiniflow/ragflow/issues/5910)).
- [x] Non-english title submitions will be closed directly ( 非英文标题的提交将会被直接关闭 ) ([Language Policy](https://github.com/infiniflow/ragflow/issues/5910)).
- [x] Please do not modify this template :) and fill in all the required fields.

### Describe your problem

When I use the code component in the agent, the following error occurs during runtime:
 module 'agent.tools' has no attribute 'CodeExecParam'
 Traceback (most recent call last):
   File "/ragflow/agent/component/__init__.py", line 55, in component_class
     return getattr(m, class_name)
 AttributeError: module 'agent.component' has no attribute 'CodeExecParam'
 
 During handling of the above exception, another exception occurred:
 
 Traceback (most recent call last):
   File "/ragflow/api/apps/canvas_app.py", line 184, in reset
     canvas = Canvas(json.dumps(user_canvas.dsl), current_user.id)
   File "<@beartype(agent.canvas.Canvas.__init__) at 0x75c569b48670>", line 31, in __init__
   File "/ragflow/agent/canvas.py", line 111, in __init__
     self.load()
   File "/ragflow/agent/canvas.py", line 123, in load
     param = component_class(cpn["obj"]["component_name"] + "Param")()
   File "/ragflow/agent/component/__init__.py", line 57, in component_class
     return getattr(importlib.import_module("agent.tools"), class_name)
 AttributeError: module 'agent.tools' has no attribute 'CodeExecParam'

**Comment by KevinHuSh** [comment]
The agent is no longer compatible to the previous versions.

**Comment by qazwsx18** [comment]
[@dosu](https://go.dosu.dev/dosubot)I apologize for the disturbance. I have deleted the migrated agent and rebuilt it entirely in the new version. However, the code component still exhibits the same issue. Perhaps this is a bug?

**Comment by chengtm** [comment]
Some error.
