### PR TITLE
fix(api): re-authorize owner_ids on /chats and /searches (#15741)

### LINKED ISSUE #15741: [Question]: Unexpected Chat Apps Appearing in Chat Page and Causing Frontend ErrorSomething went wrong
### Self Checks

- [x] I have searched for existing issues [search for existing issues](https://github.com/infiniflow/ragflow/issues), including closed ones.
- [x] I confirm that I am using English to submit this report ([Language Policy](https://github.com/infiniflow/ragflow/issues/5910)).
- [x] Non-english title submitions will be closed directly ( 非英文标题的提交将会被直接关闭 ) ([Language Policy](https://github.com/infiniflow/ragflow/issues/5910)).
- [x] Please do not modify this template :) and fill in all the required fields.

### Describe your problem

Sorry, an error occurred while loading the page.

Error details

TypeError: x.find is not a function

Reload Page

Description

After upgrading RAGFlow, several Chat Apps that do not belong to my workspace suddenly appeared on the Chat page.

These unexpected Chat Apps are visible in the Chat Apps list, but when I click any of them, the page fails to load and shows the following error:

Something went wrong

Sorry, an error occurred while loading the page.

Error details:
TypeError: x.find is not a function
Expected Behavior

Only Chat Apps that belong to the current workspace/user should be displayed.

Actual Behavior

Additional unknown Chat Apps appear in the Chat page. Opening any of these Chat Apps results in a frontend error:

TypeError: x.find is not a function

and the page cannot be loaded.

Environment
RAGFlow Version: v0.25.6
Deployment Method: Docker Compose
Browser: [Please specify]
OS: Ubuntu Server
Additional Information

The issue appeared after upgrading RAGFlow. Before the upgrade, these unexpected Chat Apps were not visible.

If needed, I can provide screenshots and browser console logs.

### PR DESCRIPTION
**Pull request by Rene0422**
## Summary

Fixes #15741.

After upgrading to v0.25.6, users see chat apps that don't belong to their workspace and the chat page crashes with `TypeError: x.find is not a function` when they click one. There are two problems, both regressed by recent merges:

### 1. Backend: cross-tenant data leak on `/api/v1/chats` and `/api/v1/searches`

PR #14775 ("authorize owner_ids for list chats and search apps") was reverted by [#15698](https://github.com/infiniflow/ragflow/pull/15698) on 2026-06-05. The reverted state of [api/apps/restful_apis/chat_api.py:462-476](api/apps/restful_apis/chat_api.py#L462-L476) and [api/apps/restful_apis/search_api.py:87-95](api/apps/restful_apis/search_api.py#L87-L95) accepts client-supplied `owner_ids` straight from the query string and passes them into:

```python
chats, total = await thread_pool_exec(
    DialogService.get_by_tenant_ids,
    owner_ids, current_user.id, 0, 0, orderby, desc, keywords, **exact_filters,
)
chats = [chat for chat in chats if chat["tenant_id"] in owner_ids]
```

Which generates SQL ``WHERE tenant_id IN owner_ids OR tenant_id = current_user.id`` followed by a Python filter that keeps only `tenant_id IN owner_ids`. **The net effect is that any authenticated user can list any tenant's chats / search apps by guessing tenant IDs in the query string.**

The CodeRabbit review on #15698 already called this out at merge time:

> The reverted code passed request-supplied `owner_ids` directly to backend services without server-side validation. This allowed any authenticated user to enumerate resources (chats and search apps) belonging to arbitrary tenants by simply supplying their IDs.

### 2. Frontend: chat page crashes on non-array response

When the backend rejects a request mid-flight (e.g. `data: false, message: "No authorization"`), `useFetchSessionList` / `useFetchChatList` return `data?.data`, which becomes the non-array reject value. Two `.find()` call sites then crash:

- [web/src/pages/next-chats/chat/index.tsx:44](web/src/pages/next-chats/chat/index.tsx#L44) — `dialogList.find((x) => x.id === conversationId)`
- [web/src/pages/next-chats/hooks/use-select-conversation-list.ts:18](web/src/pages/next-chats/hooks/use-select-conversation-list.ts#L18) — `data.chats.find((x) => x.id === dialogId)`

This is what produces the user's reported `TypeError: x.find is not a function`.

### Backend — re-add the authorization gate from #14775

In `list_chats` and `list_searches`, when `owner_ids` is supplied:

1. Compute `authorized_owner_ids = {tenant_id for tenant in TenantService.get_joined_tenants_by_user_id(current_user.id)} ∪ {current_user.id}`.
2. If any requested `owner_id` is outside that set, log the rejected attempt and return `data=False, message="Only authorized owner_ids can be queried.", code=RetCode.OPERATING_ERROR`.
3. Otherwise proceed with the existing query path unchanged.

I deliberately did **not** re-apply the broader behaviour change from #14775 (defaulting to all authorized tenants when no `owner_ids` is supplied, and DB-level pagination across that combined set). That broader change may have been the actual motivation for the revert in #15698. The no-`owner_ids` branch is left as-is — it still restricts to `tenant_id == current_user.id`, so personal-chat visibility is unaffected by this PR.

### Frontend — guard the two `.find()` sites

Wrap with `Array.isArray(...) ? ... : []` before calling `.find()`. This catches the rejection-response shape so the page doesn't crash even if a stale tab gets a server error or a non-200 with a non-array body.

## What this PR does NOT change

- `DialogService.get_by_tenant_ids` / `SearchService.get_by_tenant_ids` SQL — unchanged.
- The no-`owner_ids` query path — unchanged.
- Pagination behaviour — unchanged (still in-Python for the `owner_ids` branch, matching the reverted state).
- No new tests. The original PR #14775 added test cases; those were also reverted, and re-creating them is a bigger undertaking better handled as a follow-up so this can land quickly to close the leak.

## Test plan

- [ ] As user A (tenant T_A): `GET /api/v1/chats` returns only T_A's chats — no change in behaviour.
- [ ] As user A: `GET /api/v1/chats?owner_ids=T_B` where A does not belong to T_B → expect `code=OPERATING_ERROR`, message "Only authorized owner_ids can be queried.", and a warning log line with the rejected owner_ids.
- [ ] As user A: `GET /api/v1/chats?owner_ids=T_A` where A belongs to T_A → returns T_A's chats (unchanged).
- [ ] Same three cases against `GET /api/v1/searches`.
- [ ] In the browser, open `/next-chats/chat/<conversationId>` while the chat-list request is in-flight; rapidly switch dialogs to force a stale-response race — page no longer crashes with `x.find is not a function`.

## Files changed

- [api/apps/restful_apis/chat_api.py](api/apps/restful_apis/chat_api.py) — `list_chats` authorizes `owner_ids` against the user's joined tenants ∪ own id.
- [api/apps/restful_apis/search_api.py](api/apps/restful_apis/search_api.py) — `list_searches` does the same.
- [web/src/pages/next-chats/chat/index.tsx](web/src/pages/next-chats/chat/index.tsx) — `Array.isArray` guard before `dialogList.find`.
- [web/src/pages/next-chats/hooks/use-select-conversation-list.ts](web/src/pages/next-chats/hooks/use-select-conversation-list.ts) — `Array.isArray` guard before `data.chats.find`.

### Type of change

- [x] Bug Fix (non-breaking change which fixes an issue)
- [ ] New Feature (non-breaking change which adds functionality)
- [ ] Documentation Update
- [ ] Refactoring
- [ ] Performance Improvement
- [ ] Other (please describe):

### CODE REVIEW

**Comment by JinHai-CN** [comment]
@Rene0422 would you please resolve the conflicts?
