### PR TITLE
fix(rag): unify parser_config delimiter defaults on a single constant

### LINKED ISSUE #18562: [Bug] Default delimiter varies across 11 sites; parser_config.get defaults diverge per file type, producing different chunk counts for English text
## Self Checks

- [x] I have searched for existing issues — #18552 covers the surrounding `custom delimiter` bug but not the defaults specifically
- [x] I confirm English-only title
- [x] Template preserved

## Summary

The default delimiter for `parser_config.delimiter` is set in **at least 11 places** across the codebase, with **4 distinct values**. The shipped defaults diverge by callback site, and the divergence is large enough to produce a real chunk-count difference for the same input text. There is no single source of truth.

The codebase has never had a guiding question of "what should the default delimiter be?" — every new parser path has copy-pasted whichever default was nearby, and the inconsistency has accumulated silently.

## Environment

- RAGFlow: v0.27.0 (`ec9c08d80`, tag `v0.27.0`)
- Affected files: `rag/app/naive.py`, `deepdoc/parser/txt_parser.py`, `rag/app/email.py`, `rag/app/book.py`, `rag/nlp/__init__.py`, `web/src/components/chunk-method-dialog/use-default-parser-values.ts`, `web/src/pages/dataset/dataset-setting/index.tsx`, `web/src/components/delimiter-form-field.tsx`

## The 11 defaults

Grouped by category:

### Group 1 — UI defaults (the value the user sees and submits)

| Location | Default | `parsed_dels` |
|---|---|---|
| `web/src/components/chunk-method-dialog/use-default-parser-values.ts:30` | `'\n'` | `['\n']` (1) |
| `web/src/pages/dataset/dataset-setting/index.tsx:71` | `'\n'` | `['\n']` (1) |
| `web/src/components/delimiter-form-field.tsx:78` (fallback when `field.value` is `undefined`) | `'\n'` | `['\n']` (1) |

The three agree: `'\n'` (single newline). This is the user's "safe minimum" — no surprises.

### Group 2 — Python function signature defaults (effectively dead code)

| Location | Default | `parsed_dels` |
|---|---|---|
| `rag/nlp/__init__.py:1366` `naive_merge` | `'\n。；！？'` | `['\n', '。', '；', '！', '？']` (5, Chinese-only) |
| `rag/nlp/__init__.py:1429` `naive_merge_with_images` | `'\n。；！？'` | same |
| `rag/nlp/__init__.py:1785` `naive_merge_docx` | `'\n。；！？'` | same |
| `deepdoc/parser/txt_parser.py:30` `RAGFlowTxtParser.__call__` | `'\n!?;。；！？'` | `['\n', '!', '?', ';', '。', '；', '！', '？']` (8, full set) |
| `deepdoc/parser/txt_parser.py:35` `RAGFlowTxtParser.parser_txt` | `'\n!?;。；！？'` | same |

These trigger only when the function is called **without** `parser_config`, which only happens in unit tests. In production (`rag/svr/task_executor.py:360`), `chunker.chunk()` is always called with `parser_config=parser_config_for_chunk`, so these defaults are unreachable for real users.

But they encode the maintainers' mental model of "the default delimiter" — and the two camps disagree: 3 functions say `'\n。；！？'`, 2 say `'\n!?;。；！？'`.

### Group 3 — `parser_config.get` defaults (the ones that ship)

| Location | Default | `parsed_dels` |
|---|---|---|
| `rag/app/naive.py:1137` (txt) | `'\n!?;。；！？'` | 8 delims |
| `rag/app/naive.py:1149` (markdown) | `'\n!?;。；！？'` | 8 delims |
| `rag/app/naive.py:1030` (docx) | `'\n!?。；！？'` | **7 delims (no `;`)** |
| `rag/app/naive.py:1304` (image) | `'\n!?。；！？'` | **7 delims (no `;`)** |
| `rag/app/email.py:102` | `'\n!?。；！？'` | **7 delims (no `;`)** |
| `rag/app/book.py:184` | `'\n。；！？'` | **5 delims (Chinese-only)** |

These are the ones that actually reach users. The `parser_config.get` fallback is consulted when the user has set `parser_config` but the `delimiter` key is missing (e.g. they didn't fill the field). Across 5 file types, the divergence is:

- **txt, markdown** — full set including `;`
- **docx, image, email** — same set minus `;`
- **book** — Chinese-only, no English punctuation at all

There is no consistent reason for this split. Both `.txt` and `.docx` typically contain English text; both contain semicolons. The `;` is a hard sentence-clause separator in English prose. Removing it from `.docx` parsing causes chunking inconsistency: the same paragraph of text with a semicolon produces one chunk in `.txt` and a different (possibly oversize) chunk in `.docx`.

## Why the split is almost certainly drift, not design

I traced the defaults through git history. The diverging values predate the recent refactors (#17383 / #17203 / #17808) — they've been in the codebase for a long time. There's no commit message or comment that explains why docx and email chose `'\n!?。；！？'` while txt and markdown chose `'\n!?;。；！？'`.

The closest thing to a designed choice is the `book.py:184` default `'\n。；！？'` (Chinese-only). The book parser is commonly used for Chinese/foreign-language books, and a Chinese-only default makes sense for that audience. But the rest of the divergence is unexplained.

## Reproduction

This is a 10-line audit script anyone can run from the repo root:

```python
from rag.nlp.delim import parse_delimiter_field

defaults = [
    ("chunk-method-dialog/use-default-parser-values.ts:30", "\n"),
    ("dataset-setting/index.tsx:71", "\n"),
    ("delimiter-form-field.tsx:78", "\n"),
    ("naive_merge signature", "\n。；！？"),
    ("naive_merge_with_images signature", "\n。；！？"),
    ("naive_merge_docx signature", "\n。；！？"),
    ("TxtParser.__call__ signature", "\n!?;。；！？"),
    ("TxtParser.parser_txt signature", "\n!?;。；！？"),
    ("naive.py:1137 (txt)", "\n!?;。；！？"),
    ("naive.py:1149 (markdown)", "\n!?;。；！？"),
    ("naive.py:1030 (docx)", "\n!?。；！？"),
    ("naive.py:1304 (image)", "\n!?。；！？"),
    ("email.py:102", "\n!?。；！？"),
    ("book.py:184 (book)", "\n。；！？"),
]

distinct_values = sorted(set(v for _, v in defaults))
print(f"Distinct defaults in production: {len(distinct_values)}")
for v in distinct_values:
    print(f"  {v!r}  -> parsed: {parse_delimiter_field(v)}")
```

**Expected output** (on any current `main`):

```
Distinct defaults in production: 4
  '\n'                                         -> parsed: ['\n']
  '\n!?;。；！？'                              -> parsed: ['\n', '!', '?', ';', '。', '；', '！', '？']
  '\n!?。；！？'                                  -> parsed: ['\n', '!', '?', '。', '；', '！', '？']
  '\n。；！？'                                  -> parsed: ['\n', '。', '；', '！', '？']
```

## The user-visible effect

Measured on a 2101-token sample with `.` after every sentence (no `\n`):

| Default | `parsed_dels` count | Chunks for the sample | Per-file-type scope |
|---|--:|--:|---|
| `'\n'` (UI) | 1 | 1 (oversized, 2102 tokens) | hypothetical fall-through |
| `'\n!?;。；！？'` (txt, markdown) | 8 | 3 (490–1002 tokens) | .txt, .md |
| `'\n!?。；！？'` (docx, image, email) | 7 | 3 (490–1002 tokens) | .docx, image, .eml |
| `'\n。；！？'` (book, naive_merge signatures) | 5 | 1 (oversized, 2102 tokens) | .book, hypothetical fall-through |

For text with normal newlines the four values converge because newlines dominate the splits. For text **without newlines but with punctuation** — OCR'd PDFs, copy-pasted prose, normalized text — the values diverge:

- `'\n!?;。；！？'` (txt, markdown) splits correctly on every sentence boundary.
- `'\n!?。；！？'` (docx, image, email) splits correctly on every sentence boundary too, except at `;` — so a paragraph like "The rain; the sun; the wind" becomes one oversized chunk instead of three.
- `'\n。；！？'` (book) **misses every English sentence boundary** because it has no English punctuation. The same paragraph with English punctuation produces one giant chunk.

This is a latent bug. PR #17203 didn't touch it because the reporter's data had newlines. Users with OCR-normalized or paragraph-stripped text will hit it. The robustness fix is to consolidate to one default.

## Suggested fix

A single source of truth for the shipped default. Three concrete options:

### Option A — One constant, all `parser_config.get` calls use it

Add a constant:

```python
# rag/nlp/delim.py
DEFAULT_DELIMITER = "\n!?;。；！？"
```

Replace every `parser_config.get("delimiter", "...")` call with `parser_config.get("delimiter", DEFAULT_DELIMITER)`. Apply the same to the UI default in `chunk-method-dialog/use-default-parser-values.ts` (or leave the UI default at `'\n'` since that's the safe minimum).

### Option B — One `parser_config.get` default + per-file-type English-only delisting

For parsers that don't want extra English punctuation, use the function signature default. But keep the `parser_config.get` at the full set for all parsers. This loses the ability to have parser-specific defaults but gains consistency.

### Option C — Just fix the silent divergence

The minimum viable fix: change `naive.py:1030`, `naive.py:1304`, `email.py:102` to use `'\n!?;。；！？'` (the same as txt/markdown). Add `;` back. This alone removes the "no `;` for docx/email" inconsistency in 3 lines.

The function signature defaults in `rag/nlp/__init__.py` can stay as-is (dead code) but ideally also collapse to one value.

## Acceptance criteria

Any of these would prevent the issue:

- One shipped default for the main `parser_config.delimiter` field, defined as a constant and reused across all `parser_config.get` calls.
- An `assert` in the test suite that fails if `parser_config.get("delimiter", ...)` defaults diverge across parsers.
- A note in the developer docs (or in the `delim.py` module docstring) explaining the intent behind the shipped default and why one value fits all parsers.

## Workaround (today)

There's no per-dataset escape hatch. If a user hits the English-punctuation gap in `.docx`, they have to switch the parser to `naive` (general) or pre-process the file to substitute `;` for `;` (or vice versa). Not documented.

## Related

- #18552 — the surrounding `custom delimiter` bug. The defaults divergence is the prerequisite for the "no `;`" sub-case of that bug.
- #17202 — the broader `chunk_token_num` ignored bug. The defaults divergence is one of several open angles.
- #17203 — fixed the soft-cap overshoot but did not touch the defaults.
- #17275 — open PR for hard-cap enforcement in `naive_merge` / `naive_merge_with_images` / `RAGFlowTxtParser`. Doesn't touch defaults either.
- #17692 — open PR for `naive_merge_docx`. Doesn't touch defaults.
- #16959 — open PR for `book.py` / `paper.py` chunking. Doesn't touch defaults.

### PR DESCRIPTION
**Pull request by euvre**
### Summary

**Background.** The default for `parser_config.delimiter` was set independently in 20+ backend places with four distinct values, so the shipped fallback differed by file type: txt/markdown merged with `"\n!?;。；！？"` while docx/image/email omitted the ASCII `;`, the `naive_merge*` signatures carried the Chinese-only `"\n。；！？"`, and `rag/svr/task_executor.py` (plus its refactor twin `chunk_service.py`) injected the `;`-less set whenever a dataset's parser_config lacked the key. Result (#18562): the same English semicolon-separated paragraph produced different chunk counts depending on file type — at `chunk_token_num=32` the txt default yields 2 chunks while the docx/email default yields one oversized chunk. There was no single source of truth; every new parser path copy-pasted whichever default was nearby.

**Fix.**

- Define the 8-character set once: `DEFAULT_DELIMITER = "\n!?;。；！？"` in `rag/nlp/delim.py` (the module that already owns the canonical delimiter *parser*), re-exported from `rag.nlp`.
- Point every backend default at the constant:
  - `rag/app/naive.py`: the txt / markdown / docx / image / naive `parser_config.get("delimiter", ...)` merge fallbacks and the kwargs default dict;
  - `rag/app/email.py`: kwargs default dict + merge fallback;
  - `rag/app/laws.py`, `one.py`, `manual.py`, `paper.py`: kwargs default dicts (the `delimiter` key is unused there today, but it was a copy-paste landmine);
  - `rag/svr/task_executor.py` and `rag/svr/task_executor_refactor/chunk_service.py`: the injection/recording sites that materialize the delimiter when the DB config lacks it;
  - `rag/nlp/__init__.py` (`naive_merge`, `naive_merge_with_images`, `naive_merge_docx`) and `deepdoc/parser/txt_parser.py` signature defaults;
  - `api/db/services/file_service.py` and `rag/flow/parser/parser.py` already used the 8-char set — their literals now reference the constant too.
- Keep `rag/app/book.py` untouched: its `"\n。；！？"` merge default is the deliberate Chinese-prose choice (the "except perhaps chinese" carve-out discussed in the issue), now pinned by a regression guard so it reads as a decision rather than drift.
- Go parity: the ingestion port's `sentenceDelimiter` (documented mirror of naive_merge's production delimiter) gains `;` to match the unified set; its pin test and the mirror comments are updated.
- New regression tests in `test/unit_test/rag/nlp/test_default_delimiter_constant.py`: pin the constant value and its 8 parsed delimiters; AST-walk every backend file to assert no raw string default can be re-introduced; guard the book carve-out; assert the `naive_merge*` signatures carry the constant; and a behavioral test showing semicolon prose splits under the unified default but stays whole under the pre-fix docx default.

**Behavior change:** docx / image / email documents (and any parser_config without an explicit `delimiter` key) now chunk semicolon-separated English text exactly the way txt/markdown already did. Datasets created through the UI or the HTTP API always carry an explicit `delimiter: "\n"` and are unaffected.

**Verification.** All delimiter/merge/API-default unit tests pass (128 tests across `test/unit_test/rag/` and `test/unit_test/api/utils/test_default_delimiter.py`, including the 5 new ones), the deepdoc txt_parser suite passes (8 tests), and `go test ./internal/ingestion/component/chunker/...` passes. The Go run used `CGO_ENABLED=0` because this sandbox lacks `ld.lld` for the native pdfium static link; the changed Go code is a pure regex/comment change. No browser end-to-end run was performed: the divergent defaults only fire when `parser_config` lacks the `delimiter` key, which the UI/API always set at dataset-creation time, so the divergence is not reachable through the normal UI flow — evidence is direct invocation of the shipped chunking functions (the repro in the issue discussion) plus the regression tests above.

Fixes #18562

### CODE REVIEW

**Review by wangq8 — COMMENTED** [review]
Excellent work — this is exactly the right fix for #18562. The PR body is thorough, the single source of truth (`DEFAULT_DELIMITER` in `rag/nlp/delim.py`) is well-placed (the module that already owns the delimiter parser), and the AST-based regression tests are a great way to prevent silent re-drift.

I verified the key risks locally against `ragflow-main`:

- **Signature default change is safe.** `naive_merge` / `naive_merge_with_images` / `naive_merge_docx` change their default from `"\n。；！？"` to `DEFAULT_DELIMITER`. All in-repo callers (`rag/app/naive.py`, `rag/app/email.py`, `rag/flow/chunker/token_chunker.py`, `rag/flow/compiler/compiler.py`) pass an explicit `delimiter`, so no call site silently changes behavior. Confirmed.
- **`parse_delimiter_field(DEFAULT_DELIMITER)`** returns `["\n", "!", "?", ";", "。", "；", "！", "？"]` (stable length-1 sort preserves first-occurrence order), matching the test assertion.
- **Go parity** (`sentenceDelimiter` gains `;`, `sentenceBoundaryRe` left alone) is consistent with the two-distinct-Python-constants rationale and the updated pin test.

A few nits / suggestions:

1. **Magic number in the guard test.** `assert checked >= 17` is a floor, not an exact bound — if a site is later removed (or a default deleted), the test can still pass as long as ≥17 remain. Consider asserting per-file minimums or the exact count so a deletion actually fails loudly.

2. **book.py carve-out only pins the `.get` fallback.** `rag/app/book.py` actually carries *two* divergent defaults — the kwargs dict `"\n!?。；！？"` (line 70) and the merge fallback `"\n。；！？"` (line 184). `test_book_keeps_its_deliberate_chinese_only_default` only asserts the latter. That's fine given the carve-out is intentional, but the PR body's "keeps its own Chinese-only default" describes only the merge fallback, not the kwargs dict. A one-line comment on that dict would make the intent unambiguous for the next reader.

3. **Behavior change beyond docx/image/email.** The `naive_merge*` signature default change means any *future* caller omitting `delimiter` gets the full 8-char set (including ASCII `!?;`) rather than the old Chinese-only set. That's the intended unification, but worth one sentence in the commit message so it reads as deliberate.

No blocking issues — this LGTM. Nice test coverage, especially the behavioral semicolon-prose test that pins the exact reported symptom.

**Comment by euvre** [comment]
Hi @wangq8 — thanks for the thorough review, and for locally verifying the signature-default safety and the Go parity. All three nits are addressed in ebaa483ef:

1. **Guard test floor → exact per-file counts.** The `SITES_USING_CONSTANT` list + aggregate `assert checked >= 17` is replaced by `EXPECTED_DELIMITER_DEFAULTS`, an ordered map of file → exact number of `delimiter` defaults (21 across 12 files). Each file now asserts its exact count before the `DEFAULT_DELIMITER` check, so deleting a fallback — or adding a new default without updating the table — fails loudly with a per-file message. Verified positively (28 tests pass, including the 23 `test_naive_merge.py` cases) and negatively: simulating a one-site deletion for `rag/app/naive.py` trips `expected exactly 5 delimiter defaults, found 6`.

2. **book.py carve-out.** Added the intent comment on the kwargs dict (it and the merge fallback deliberately keep Chinese-only sets, not the unified constant) and extended `test_book_keeps_its_deliberate_chinese_only_default` to pin **both** values — the kwargs dict `"\n!?。；！？"` and the merge fallback `"\n。；！？"` — so the carve-out is now pinned in full, not just documented. The test-module docstring now says "defaults" (plural) to match.

3. **Deliberate-change note.** The branch is a single already-pushed commit, so rather than rewriting history I carried the sentence into the new commit's message: the `naive_merge*` signature defaults now resolve to `DEFAULT_DELIMITER`, so any future caller omitting `delimiter` gets the full 8-character set (including ASCII `!?;`) instead of the old Chinese-only `"\n。；！？"` — the intended unification, not drift.

Verification for this round: `pytest test/unit_test/rag/nlp/test_default_delimiter_constant.py test/unit_test/rag/test_naive_merge.py` → 28 passed; `ruff check` / `ruff format --check` clean under the repo config. The only production-file change is one comment in `rag/app/book.py` (no runtime behavior change), so container-level e2e was not warranted this round.

**Comment by wangq8** [comment]
LGTM.  @euvre please fix the unit tests failure

**Review by wangq8 — APPROVED** [review]

**Comment by euvre** [comment]
Hi @wangq8 — thanks for the thorough review and the approval! The unit-test failure you flagged was fixed in 1136e0bde, and the full CI matrix went green on that commit (python + go, both Infinity and Elasticsearch) before the merge — no further changes were needed.

What had broken: the 09-03 sync with `main` (30820cba4) brought in `test/unit_test/rag/test_naive_dispatch.py`, whose `naive_module` fixture stubs `rag.nlp` before importing `naive.py`. Since this PR makes `naive.py` import the unified constant from `rag.nlp`, the stub was missing `DEFAULT_DELIMITER`, so every test using that fixture failed at setup with `ImportError: cannot import name DEFAULT_DELIMITER` (visible as the `ragflow_preflight` failure on 30820cba4). The fix adds the constant to the stub with the exact `rag/nlp/delim.py` value (`"\n!?;。；！？"`) — the dispatch tests never read it, only the name must exist — and all checks passed on 1136e0bde.

Your three earlier nits were all addressed in ebaa483ef as summarized in my previous comment: exact per-file delimiter-default counts via `EXPECTED_DELIMITER_DEFAULTS`, the `book.py` carve-out comment with both Chinese-only defaults pinned, and the deliberate future-caller behavior change recorded in the commit message. Thanks again for the careful review — glad the #18562 unification landed!
