### ISSUE TITLE
[Bug]: MCP server crashes on tools/list - list_chats() assumes /chats API returns a list but gets a dict

### ISSUE THREAD

**Issue by BAIGUANGMEI** [infiniflow/ragflow#16638]
### Self Checks

- [x] I have searched for existing issues, including closed ones.
- [x] I confirm that I am using English to submit this report.
- [x] Non-english title submissions will be closed directly.

### RAGFlow image version

v0.26.3

### Other environment information

```
Linux 6.17.0-29-generic, Docker deployment (CPU image)
```

### What happened

The MCP server crashes on **every** `tools/list` request with:

```
'str' object has no attribute 'get'
```

This makes **all three MCP tools** (`ragflow_retrieval`, `ragflow_list_datasets`, `ragflow_list_chats`) completely unavailable to any MCP client.

### How to reproduce

1. Start RAGFlow v0.26.3 with MCP server enabled (host or self-host mode).
2. Connect any MCP client and send a `tools/list` request.
3. The server returns an error instead of the tool list.

**Root cause:**

The `list_chats()` method in `mcp/server/server.py` (line 185-188) assumes the `/api/v1/chats` REST API returns `data` as a **list**:

```python
chat_count = len(res_json.get("data", []))   # line 185
for data in res_json.get("data", []):         # line 188
    d = {"id": data.get("id"), ...}
```

However, the `/api/v1/chats` endpoint returns a **paginated envelope** (dict, not list):

```json
{
  "code": 0,
  "data": {
    "chats": [...],
    "total": 1
  }
}
```

When iterating a dict, Python yields its **keys** (strings `"chats"`, `"total"`). Calling `.get("id")` on a string then raises `'str' object has no attribute 'get'`.

### Expected behavior

The MCP server should handle both response shapes (list and dict-with-`chats`-key) and return the tool list successfully.

### Additional context

This bug was introduced in PR #15384 (feat(mcp): add ragflow_list_datasets and ragflow_list_chats tools), which was merged into v0.26.x. The `list_datasets()` method already handles the `data` field correctly for the `/datasets` endpoint (which returns a list), but `/chats` has a different response shape.

A broader fix is proposed in PR #15796 (unify REST API response envelope), but that is a large refactoring PR still under review. This issue requests a targeted fix for the MCP server only.

I have submitted a fix PR for this issue.
